### PR TITLE
Order bug fix and user update change

### LINKED ISSUE #131: bug/items-not-shown-in-findByUser-order-route
## Describe the bug
When searching for all the orders by a user, it is expected that the items attached to the order should also show up. This is not the case at the moment

## To Reproduce
1. Sign in as a user with some orders
2. Use the `orders/findByUser` route
3. No items show up with the list of orders

## Expected behavior
A list of items should appear with each entry in the order

## Screenshots
Order as seen with `findByUser` route
image

Order as seen with `all` route
image

### PR DESCRIPTION
**Pull request by KooshaG**
## Brief Description
Fixed bug where items didn't show up in `findByUser` route. Updated functionality of `/users/update` so that the user's password is always required

## Linked Issues
- closes #131 

## Changes
- Updated Wiki to reflect changes
- Added items to order route
- Users now need to provide their password in the request to update their profile
- Fixed crashing issue with `signin` because of having a function run after sending headers
- Added new route:
  - Original `find` is now `findByItem`
  - `find` now looks up orders by the id **of the order itself**

## Acceptance Criteria
- [x] Test coverage >80%
- [x] All specifications met in feature requirements

### CODE REVIEW

File: online-shopping-website/backend/src/routes/users.ts [hunk 1]
```diff
@@ -67,8 +67,12 @@ userRouter.post('/update', async (req: Request, res: Response) => { // updates a
     if (usr === null || usr === undefined) {
       throw new Error(`Authentication is invalid`);
     }
+    const match = await bcrypt.compare(req.body.oldPassword, usr.password);
+    if (!match){
+      throw new Error(`Password is incorrect`);
+    }
     let encrypted_password: string | undefined;
-    if (req.body.password !== undefined) {
+    if (req.body.newPassword !== undefined) {
```
Comment (Adamo-O) [inline online-shopping-website/backend/src/routes/users.ts:75]: Would we be able to change this from `newPassword` back to `password`? This change would have effects elsewhere in the app because we are setting the cookie, and other pages look for `password` instead of `newPassword`. It's not a big deal to fix, just wanted to know if this is necessary.

File: online-shopping-website/backend/src/routes/users.ts [hunk 2]
```diff
@@ -67,8 +67,12 @@ userRouter.post('/update', async (req: Request, res: Response) => { // updates a
...
       //new password
       encrypted_password = await bcrypt.hash(req.body.password, 5);
```
Comment (Adamo-O) [inline online-shopping-website/backend/src/routes/users.ts:77]: This tries to hash `req.body.password` instead of `req.body.newPassword` is this correct?

File: online-shopping-website/backend/src/routes/users.ts (hunk 1 above)
Comment (KooshaG) [reply online-shopping-website/backend/src/routes/users.ts:75]: Yeah its possible but it might make things a little more difficult to read. If it makes it easier for the front end then i can switch it back

File: online-shopping-website/backend/src/routes/users.ts (hunk 2 above)
Comment (Adamo-O) [reply online-shopping-website/backend/src/routes/users.ts:77]: I get what you mean. But on line 77, it does `bcrypt.hash(req.body.password, 5)`. As per the wiki, you take in `oldPassword` as a key, not `password`. I just want to make sure I'm sending the correct body key/value pairs. Doesn't `password` no longer exist in the request body?

Comment (KooshaG) [reply online-shopping-website/backend/src/routes/users.ts]: Yeah thats my bad, i reverted back to `password` so that there's no confusion

**Review by Adamo-O — APPROVED** [review]
Mostly quote changes but all other changes look good!
